# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 09:06
from __future__ import unicode_literals

import core.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_transaction_settlement_date'), ('core', '0003_party_projects'), ('core', '0004_auto_20161205_1506'), ('core', '0005_auto_20161206_1856'), ('core', '0006_auto_20161206_1918'), ('core', '0007_auto_20161207_0940'), ('core', '0008_auto_20161207_0942'), ('core', '0009_auto_20161207_0943'), ('core', '0010_auto_20161207_1021'), ('core', '0011_auto_20161207_1034'), ('core', '0012_auto_20161207_1043'), ('core', '0013_auto_20161207_1043'), ('core', '0014_auto_20161207_1053'), ('core', '0015_auto_20161207_1220'), ('core', '0016_auto_20161207_1221'), ('core', '0017_auto_20161207_1226'), ('core', '0018_auto_20161207_1253'), ('core', '0019_auto_20161207_1356'), ('core', '0020_auto_20161212_1516'), ('core', '0021_auto_20161214_0939'), ('core', '0022_auto_20161214_1349'), ('core', '0023_auto_20161221_1523'), ('core', '0024_auto_20161222_0927')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('is_domestic', models.BooleanField(default=True)),
                ('vat_ptc', models.IntegerField(default=25, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('is_internal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('1', 'incoming'), ('2', 'outgoing')], default=1, max_length=1)),
                ('transaction_type', models.CharField(choices=[('1', 'invoice'), ('2', 'tax'), ('3', 'payroll'), ('4', 'profit'), ('5', 'adjustment')], default=1, max_length=1)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('settlement_ammount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('description', models.CharField(default='', max_length=1024)),
                ('comments', models.TextField(default='')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Party')),
                ('settlement_date', models.DateField(blank=True, default=None, null=True)),
                ('invoice_date', models.DateField(default=datetime.datetime.today, verbose_name='Invoice date')),
                ('projects', models.ManyToManyField(blank=True, to='core.Project')),
                ('end_date', models.DateField(default=core.models.Transaction.calculate_last_day_of_month, verbose_name='End date')),
                ('start_date', models.DateField(default=core.models.Transaction.calculate_first_day_of_month, verbose_name='Start date')),
                ('vat_ammount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='projects',
            field=models.ManyToManyField(to='core.Project'),
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'parties'},
        ),
        migrations.AlterField(
            model_name='party',
            name='projects',
            field=models.ManyToManyField(blank=True, to='core.Project'),
        ),
    ]
