# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 15:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('is_domestic', models.BooleanField(default=True)),
                ('vat_ptc', models.IntegerField(default=25, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('is_internal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('1', 'incoming'), ('2', 'outgoing')], default=1, max_length=1)),
                ('type1', models.CharField(choices=[('1', 'invoice'), ('2', 'tax'), ('3', 'payroll'), ('4', 'profit'), ('5', 'adjustment')], default=1, max_length=1)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('settlement_ammount', models.DateField(default=0.0)),
                ('adjustment', models.DateField(default=0.0)),
                ('description', models.CharField(default='', max_length=1024)),
                ('comments', models.TextField(default='')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Party')),
            ],
        ),
    ]
