# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='settlement_date',
            field=models.DateField(null=True),
        ),
    ]
