# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_settlement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='projects',
            field=models.ManyToManyField(to='core.Project'),
        ),
    ]
