# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 14:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_party_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'parties'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Invoice date'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='projects',
            field=models.ManyToManyField(to='core.Project'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settlement_ammount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
