# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161205_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='end_date',
            field=models.DateField(default='2016-12-31', verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='start_date',
            field=models.DateField(default='2016-12-01', verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2016, 12, 6, 18, 56, 43, 863005), verbose_name='Invoice date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='projects',
            field=models.ManyToManyField(blank=True, to='core.Project'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settlement_ammount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
