# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-13 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_joblist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobList',
        ),
    ]
