# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161206_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='vat_ammount',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2016, 12, 7, 9, 40, 23, 32349), verbose_name='Invoice date'),
        ),
    ]
