# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 09:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161207_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vat_ammount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2016, 12, 7, 9, 42, 56, 788258), verbose_name='Invoice date'),
        ),
    ]
