# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161207_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2016, 12, 7, 9, 43, 27, 796449), verbose_name='Invoice date'),
        ),
    ]
