# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 10:21
from __future__ import unicode_literals

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161207_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2016, 12, 7, 10, 21, 1, 427811), verbose_name='Invoice date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vat_ammount',
            field=models.DecimalField(decimal_places=2, default=core.models.calculate_ammount, max_digits=8),
        ),
    ]
