# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 10:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161207_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2016, 12, 7, 10, 34, 21, 775798, tzinfo=utc), verbose_name='Invoice date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vat_ammount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
