# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20161207_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settlement_ammount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vat_ammount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
