# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20161207_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Transaction_type',
            new_name='transaction_type',
        ),
    ]
