# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20161207_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='settlement_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
