# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 13:49
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20161214_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='end_date',
            field=models.DateField(default=core.models.Transaction.calculate_last_day_of_month, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='start_date',
            field=models.DateField(default=core.models.Transaction.calculate_first_day_of_month, verbose_name='Start date'),
        ),
    ]
