# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 14:23
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20161214_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice_date',
            field=models.DateField(default='core.models.Transaction.get_date_today', verbose_name='Invoice date'),
        ),
    ]
